### ISSUE TITLE
Update old models

### ISSUE THREAD

**Issue by claudenirmf** [unibz-core/ontouml-models#1]
Update old models according to the newly agreed methodology. The ontologies to be updated are the following:

- [x] andersson2018ascribing
- [x] elikan2018brand
- [x] guarino2018ontological
- [x] laurier2018rea
- [x] oliveira2007towards
- [x] ahmad2018optimization
- [x] blums2018economic
- [x] fischer2018ontorea
- [x] junior2018obascid
- [x] nardi2015commitment
- [x] sales2018towards

**Comment by tgoprince** [comment]
You can remove the model from sales2018towards.

It will be replaced by the model published in 

[T. P. Sales, D. Porello, N. Guarino, G. Guizzardi, and J. Mylopoulos. Ontological foundations of competition. In S. Borgo, P. Hitzler, and O. Kutz, editors, 10th International Conference on Formal Ontology in Information Systems (FOIS), volume 306 of Frontiers in Artificial Intelligence and Applications, pages 96–109. IOS Press, 2018. doi: 10.3233/978-1-61499-910-2-96.](https://purl.org/10.3233/978-1-61499-910-2-96)

**Comment by tgoprince** [comment]
laurier2018rea was done in #19

**Comment by tgoprince** [comment]
All of these models were corrected with the exception of blums2018economic, which was removed.

The ontology developed by Blums has been updated and will be added to the dataset in the near future.
