### ISSUE TITLE
Correction on nardi2015commitment 

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/ontouml-models#134]
The folder nardi2015commitment has nardi2014formalization as the main source. According to the repository wiki page, "the Google Scholar citation key of the main source publication (e.g. nardi2015commitment)" must be used.

**Comment by claudenirmf** [comment]
The main resource used was the formalization of UFO-S, not the journal paper. The formalization presents a more detailed model which better serves the dataset in my opinion. Still, we might need to harmonize the `last-update` field and the list of references in the `.bib` file according to the decision of using the formalization as the main source.

**Comment by tgoprince** [comment]
Is the formalization on Nardi's PhD thesis?

**Comment by pedropaulofb** [comment]
Solved.
