### ISSUE TITLE
sportingbook2021

### ISSUE THREAD

**Issue by Isadoravsousa** [unibz-core/ontouml-models#156]
Fill the contributor data in the metadata-yam file of the sportingbook2021 file.

**Comment by pedropaulofb** [comment]
@Matt-81, according to our work distribution, you were the one that migrated the ontology to VP. I couldn't find the original information, but they are probably in your Google Drive. Can you please check that and [fill it in according to the latest metadata definitions available](https://github.com/unibz-core/ontouml-models/wiki/How-to-Contribute#the-ontology-metadata-file)? Thank you in advance.

**Comment by Matt-81** [comment]
@pedropaulofb The vp model was created by the students (I also gave them guidelines on how to create the files required for our repository), and all the source files are already there. I received the files from the students and then pushed them to the repository.

**Comment by pedropaulofb** [comment]
@Matt-81, I understand. The vpp part of the dataset is correct. What we need to do are two things:

1) Check if the provided reference is correct (note that there is a possible inconsistency between the dataset tourbo2021 and sportingbook2021, as reported in https://github.com/unibz-core/ontouml-models/issues/168). In this case you have to:

a) open the references.bib file and check the name of the associated work.
b) verify if the name of students that were authors of the paper.

2) Include the authors in the metadata.yaml file. For doing this:

a) Find a URI or URL that clearly identifies each one of the authors 
b) Include these URIs in the `contributor` field at the metadata.yaml file. See this field's definition at the [our wiki](https://github.com/unibz-core/ontouml-models/wiki/How-to-Contribute#the-ontology-metadata-file).

If you have any doubts, please let me know. Once again, thank you for you help!

**Comment by Matt-81** [comment]
I updated the files accordingly, cheers, mattia
