### ISSUE TITLE
Update of rodrigues2017urinary-profiles

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/ontouml-models#167]
The "Ontological Model for Urinary Profiles", presented in rodrigues2017urinary-profiles has only a single reference (to a 2015 paper). The following papers must be analyzed and the ontology or references.bib file updated.

----------------- PAPER 1
@inproceedings{rodrigues2017ontological,
  title={An ontological model for urinary profiles},
  author={Rodrigues, Fabr{\'\i}cio Henrique and Abel, Mara and Poloni, Jos{\'e} Ant{\^o}nio Tesser and Flores, Cecilia Dias and Rotta, Liane Nanci},
  booktitle={2017 IEEE 29th International Conference on Tools with Artificial Intelligence (ICTAI)},
  pages={628--635},
  year={2017},
  organization={IEEE}
}
----------------- PAPER 2
@inproceedings{rodrigues2017extending,
  title={Extending the Ontological Model for Urinary Profiles.},
  author={Rodrigues, Fabr{\'\i}cio Henrique and Poloni, Jos{\'e} Ant{\^o}nio Tesser and Flores, Cec{\'\i}lia Dias and Rotta, Liane Nanci},
  booktitle={ONTOBRAS},
  pages={33--41},
  year={2017}
}

**Comment by pedropaulofb** [comment]
@mozzherina, I have assigned this issue to you because you were responsible for migrating the original model to the Visual Paradigm. Can you please verify if the model has to be updated or not? 

By the end, please include the papers in the references.bib files if they are indeed related to the work.

Thank you in advance.

**Comment by mozzherina** [comment]
See "update-rodrigues2017urinary-profiles" branch

**Comment by pedropaulofb** [comment]
Done. Thank you @mozzherina!
