### ISSUE TITLE
Update model silveira2021oap

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/ontouml-models#177]
The author of [silveira2021oap](https://github.com/unibz-core/ontouml-models/tree/master/silveira2021oap) reported that the current version of his ontology found here in the catalog is incomplete. 

For representing the complete ontology the following model must be included:

![SAP](https://user-images.githubusercontent.com/8641647/167290909-adb25a8b-9a10-4064-bfba-9ec9a4e1678a.png)

**Comment by pedropaulofb** [comment]
@HuntedSouls, I have assigned this issue to you because you were responsible for migrating the original model to the Visual Paradigm. Thank you in advance for you contribution.

**Comment by HuntedSouls** [comment]
Solved in Pull Request #201

**Comment by pedropaulofb** [comment]
Thank you @HuntedSouls!
