### ISSUE TITLE
Broken Google Drive links at the List of UFO and OntoUML Ontology Models

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/ontouml-models#183]
Verify and remove/correct all Google Drive links at the [List of UFO and OntoUML Ontology Models](https://docs.google.com/spreadsheets/d/1JXEA3k58yAkV_jbmEc7HP9QK7RgZC5Jk1y8MR7ylFyQ/edit?usp=sharing).

Most of them are broken.

**Comment by pedropaulofb** [comment]
@Matt-81, can you please restore the models and check if the links are the same or if we have to update them?

**Comment by Matt-81** [comment]
Folders restored
