### ISSUE TITLE
Possible update in debbech2020dysfunction-analysis

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/ontouml-models#192]
Verify the relation between the following work and the one presented at the dataset [debbech2020dysfunction-analysis](https://github.com/unibz-core/ontouml-models/tree/master/debbech2020dysfunction-analysis).

[Formal specification of environmental aspects of a railway interlocking system based on a conceptual model](https://link.springer.com/chapter/10.1007/978-3-030-33223-5_28)

**Comment by pedropaulofb** [comment]
@Matt-81, I have assigned this issue to you because you were responsible for migrating the original model to the Visual Paradigm. Can you please verify if the model has to be updated or not? Thank you in advance.

**Comment by Matt-81** [comment]
@pedropaulofb I checked the new paper. The complete and most recent version of the model is the one we have (2019 vs 2020), still, I would update the bib file with the new reference, ok?

**Comment by pedropaulofb** [comment]
@Matt-81 , thank you!

Yes, you have to update the bib file with the new reference. Also, you have to include the new reference URI at the metadata.yaml file (source field). If you identify new authors, please also include them as contributors in the metadata file.

**Comment by Matt-81** [comment]
Done!

**Comment by pedropaulofb** [comment]
Thank you very much, @Matt-81!
