### ISSUE TITLE
Remove preceding slash in namespaces of TTL files

### ISSUE THREAD

**Issue by claudenirmf** [unibz-core/ontouml-models#230]
Check whether the preceding '/ ' in the namespace of TTL files prevents those files from being accessed by tools such as Protege.

If that is the case, this character must be removed across all files.

One example can be found on this [file](https://github.com/unibz-core/ontouml-models/blob/master/amaral2020rome/metadata.ttl):

```
@prefix ontouml: <https://purl.org/ontouml-models/vocabulary/>.
```

**Comment by pedropaulofb** [comment]
Thank you @claudenirmf. I've tested and all URLs below work fine with Protègè. If you think more tests are necessary, please reopen the issue informing me what more can I do.

- https://purl.org/ontouml-models/vocabulary
- https://purl.org/ontouml-models/catalog
- https://raw.githubusercontent.com/unibz-core/ontouml-models/master/amaral2020rome/metadata.ttl
- https://raw.githubusercontent.com/unibz-core/ontouml-models/master/amaral2020rome/ontology.ttl
