### ISSUE TITLE
How to name diagrams?

### ISSUE THREAD

**Issue by claudenirmf** [unibz-core/ontouml-models#6]
For the moment have not defined a standard for documenting diagrams, but there are two things we may want to capture:

- What is the source of the diagram?
- Which diagram among the original ones is the basis for the some new diagram?

One possibility is to reuse the entries of the sources in the `.bib` file like so:

```txt
nardi2015commitment/
├── original diagrams/
│   ├── nardi2015commitment-diagram1.png
│   ├── nardi2015commitment-diagram2.png
│   ├── nardi2013towards-diagram3.png
├── new diagrams/
│   ├── nardi2015commitment-diagram1.png
│   ├── nardi2015commitment-diagram2.png
│   ├── nardi2015commitment-diagram3.png
│   ├── nardi2013towards-diagram1.png
│   ├── nardi2013towards-diagram2.png
│   ├── nardi2013towards-diagram3.png
```

Still, we may drop this if we consider the added complexity and the difficult consistency checking too high.

**Comment by tgoprince** [comment]
My guess is that we will not use diagram file names for anything in this dataset, so I propose we let people name them however they want. 

I would only ask contributors to use the same name for the old and the new diagrams.

**Comment by tgoprince** [comment]
Also, why did you add figures from previous versions of the ontology? I suppose you only recreated the latest one..

**Comment by tgoprince** [comment]
We agree that we SHOULD only document the latest version of the ontology. This means we don't need to add diagrams from multiple publications, but just those which were recreated.

**Comment by claudenirmf** [comment]
Additionally, we should keep new and old diagram with matching in names in order to keep some connection between.
