### ISSUE TITLE
How to interpret generalization sets?

### ISSUE THREAD

**Issue by claudenirmf** [unibz-core/ontouml-models#7]
Should we create generalization sets on every set of generalizations shared a single connection to the general class even if not clearly stated in the model? What constraints should be assumed as default? Overlapping and incomplete?

Consider the example below of `Agent` being specialized into `Service Provider` and `Target Customer`:

<img width="1020" alt="Screen Shot 2021-11-06 at 18 20 11" src="https://user-images.githubusercontent.com/12445213/140618258-6501f669-3f08-4855-8873-aab7cb34f0cf.png">

**Comment by pedropaulofb** [comment]
Hi!

IMHO:

Should we create generalization sets on every set of generalizations shared
> a single connection to the general class even if not clearly stated in the
> model?


Yes.

What constraints should be assumed as default? Overlapping and incomplete?


Yes.

Kind regards - Cordiali saluti - Atenciosamente,
Pedro Paulo Favato Barcelos


Em sáb., 6 de nov. de 2021 às 18:21, Claudenir Fonseca <
***@***.***> escreveu:

**Comment by claudenirmf** [comment]
I think there is a broader, yet related, issue regarding hidden model information. As you can see in this [comment](https://github.com/unibz-core/ontouml-models/pull/3#pullrequestreview-803810133) I made on a recent PR, even though authors may not be explicit about cardinality constraints or association direction, the serialization <ins>will</ins> assume some default value at least.

In other words, <ins>the way we document models may change the author's original intent.</ins>

My suggestion in this regard is that you include in the diagrams all information that may be hidden in the original source. The reasoning is "if it is unavoidable that we risk changing the original's conceptualization, we should at the very least  be as clear as possible about it".

The drawback is that we lose the information about what modelers are leaving out of their models, which is also a very interesting information to have.

We may move this discussion to a new issue, but my opinion it may be better to simply rename this one.

**Comment by tgoprince** [comment]
![GS examples](https://user-images.githubusercontent.com/2519935/141315565-1ee2e7db-25ed-458e-a739-0543f3531063.png)

**Comment by tgoprince** [comment]
We decided to only assume the existence of generalization sets if there is a label or its constraints are visible.

If only the label is shown, we MUST assume that it is incomplete and overlapping.
